### ISSUE TITLE
"Wrong link!" when downloading from Chan.sankakucomplex or Gelbooru

### ISSUE THREAD

**Issue by ReEnMikki** [testertv/guillery-dl.github.io#1]
I just put links to those sites in which I was including a few tags, but the program doesn't work

**Comment by testertv** [comment]
What version of the program?


Did you add the programs gallery-dl , yt-dlp and ffmpeg, as written in the description in the folder in my program? Follow the description!


What site is not supported?

**Comment by testertv** [comment]
So, I chacked the issue. This is not a problem of my software, gallery-dl can't download images from the whole page "Chan.sankakucomplex".

As you can see some files will be downloaded, but some not.
![image](https://user-images.githubusercontent.com/61566646/209013045-0c7b1bf1-0238-423a-a925-26dcab633770.jpg)

In this case you should create issue here: https://github.com/mikf/gallery-dl/issues
